SCREEN_WIDTH = 650
SCREEN_HEIGHT = 550
SCREEN_TITLE = "chicken invaders"
BACKGROUND_1 = "./assets/background/1.jpg"
BACKGROUND_2 = "./assets/background/2.jpg"
FPS = 60
WAIT_AFTER_WIN = 3

JET_CHARACTER_SCALING = 0.2
JET_SPRITE_WIDTH = 150
JET_SPRITE_HEIGHT = 381
JET_START_CENTER_X = 100
JET_START_CENTER_Y = 100
PLAYER_MOVEMENT_SPEED = 5
JET_ANIMATION_PATH = "./assets/jet/main.png"
COUNT_JET_FRAMES = 5
PLAYER_LIST_NAME = "Players"
MOVEMENT_SPEED = 3
JET_HP = 200
JET_DAMAGE = 200

EXPLODE_ANIMATION_PATH = "./assets/explode/main.png"
COUNT_EXPLODE_FRAMES_IN_ROW = 8
COUNT_EXPLODE_FRAMES_IN_COLUMN = 4
EXPLODE_WIDTH = 256.125
EXPLODE_HEIGHT = 251.25
EXPLODE_DELAY = 0.15
EXPLODE_SOUND_TRACK_PATH = "./assets/explode/soundtrack.mp3"

BULLET_LIST_NAME = "Bullets"
LASER_BULLET_ASSET_PATH = "./assets/laser/image.png"
LASER_BULLET_SOUND_TRACK_PATH = "./assets/laser/soundtrack.mp3"
LASER_SPEED = 10
LASER_DAMAGE = 50
LASER_SCALE = 0.03

EGG_LIST_NAME = "Eggs"
EGG_SCALE = 0.025
EGG_DAMAGE = 200
EGG_SPEED = 1
EGG_ASSET_PATH = "./assets/egg/main.png"

CHICKEN_SCALING = 0.1
CHICKEN_MINIMUM_HEIGHT_LIMIT = 220
CHICKEN_START_WIDTH_RANGE = (20, SCREEN_WIDTH - 20)
CHICKEN_START_HEIGHT_RANGE = (CHICKEN_MINIMUM_HEIGHT_LIMIT, SCREEN_HEIGHT - 20)
CHICKEN_SPEED_RANGE = (-2, 2)
INIT_CHICKENS_COUNT = 10
CHICKEN_ASSET_PATH = "./assets/chicken/main.png"
CHICKEN_LIST_NAME = "Chickens"
CHICKEN_HP = 200
CHICKEN_COOLDOWN = 10
CHICKEN_DAMAGE = 200
CHICKEN_DAMAGE_COOLDOWN = 5

WALL_LIST_NAME = "Walls"

if __name__ == '__main__':
    print("This is just a config file.")
